# Top-level configuration settings
site:
  logo: /images/logo.png
  favicon: /favicon.ico
  title: My Blog
  description: A collection of thoughts and ideas.
  date_format: dd-mm-yyyy
  domain: ashishsrivastav.com
  https: true

