# Top-level configuration settings
site:
  logo: /images/logo.png
  favicon: /favicon.ico
  title: My Blog
  description: A collection of thoughts and ideas.

# Individual blog post entries
posts:
  - metadata:
      author: John Doe
      date: 2023-10-15
      tags:
        - technology
        - programming
    title: My First Blog Post
    description: A brief introduction to my blogging journey.
    url: my-first-blog-post
    filename: first-blog-post.md

  - metadata:
      author: Jane Smith
      date: 2023-10-20
      tags:
        - travel
        - photography
    title: Exploring New Horizons
    description: Capturing the beauty of nature through photography.
    url: exploring-new-horizons
    filename: exploring-horizons.md

  - metadata:
      author: Alice Johnson
      date: 2023-11-05
      tags:
        - cooking
        - recipes
    title: Culinary Adventures
    description: Sharing my favorite recipes and cooking tips.
    url: culinary-adventures
    filename: culinary-adventures.md
