name: Commit Counter

on:
  push:
    branches:
      - main

jobs:
  count-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Count Commits
        id: commit-count
        run: echo "::set-output name=commits::$(git rev-list --count HEAD)"

      - name: Display Commit Count
        run: echo "Total Commits: ${{steps.commit-count.outputs.commits}}"
